### ISSUE TITLE
PM2

### ISSUE THREAD

**Issue by gorobey** [logico/vestacp-nodejs#6]
please, can you explain in README how to install PM2?

**Comment by logico-dev** [comment]
Hi, `pm2` is out of the scope of this project. Anyway, you can install it with

```bash
$ npm install pm2@latest -g
# or
$ yarn global add pm2
```

You can find more about pm2 [here](https://pm2.keymetrics.io/docs/usage/quick-start/)

**Comment by gorobey** [comment]
@logico-dev tnx!
