### ISSUE TITLE
can you explain this step: The app must listen on a UNIX socket in /home/user/web/domain/nodeapp/app.sock

### ISSUE THREAD

**Issue by orgolan** [logico/vestacp-nodejs#8]
I made all the steps but i couldnt see any app.sock generated
when i tried to access the domain i got 500 error:
 connect() to unix:/home/admin/web/website/nodeapp/app.sock failed (13: Permission denied) while connecting to upstream

**Comment by logico-dev** [comment]
Normally the app listen on some TCP port, 3000 ie, then you access through that port `http://localhost:3000`. With this template you need to use a UNIX socket instead. To do that, you need to change the port parameter to the path of the app ie: `/home/your_user/web/a_sample_webapp/nodeapp/app.sock`. Here is the documentation for [server.listen()](https://nodejs.org/api/net.html#net_server_listen)

https://nodejs.org/en/docs/guides/getting-started-guide/

```
const http = require('http');

const hostname = '127.0.0.1';
const port = '/home/your_user/web/a_sample_webapp/nodeapp/app.sock';

const server = http.createServer((req, res) => {
  res.statusCode = 200;
  res.setHeader('Content-Type', 'text/plain');
  res.end('Hello World');
});

server.listen(port, hostname, () => {
  console.log(`Server running at http://${hostname}:${port}/`);
});
```

**Comment by activemonkeys** [comment]
Thanks logico-dev, that already helps. One more question, how do you create the app.sock file on a Ubuntu 18.04 system with VestaCP installed. Many thanks!

**Comment by logico-dev** [comment]
> Thanks logico-dev, that already helps. One more question, how do you create the app.sock file on a Ubuntu 18.04 system with VestaCP installed. Many thanks!

NodeJS creates the app.sock file at runtime.
