### ISSUE TITLE
connect() to unix .... app.sock failed (2: No such file or directory) while connecting to upstream

### ISSUE THREAD

**Issue by hassaan-dev** [logico/vestacp-nodejs#9]
Hello,

My VPS is running on CentOS 7 with VestaCP apache + nginx 
I install nodejs 10 and followed your steps and rebuild web config for admin user to make sample app.

I am getting the following 500 error in error logs, when ever I tried to open website

>2020/05/04 18:33:47 [crit] 5009#5009: *1 connect() to unix:/home/admin/web/movies-app.saedhamdan.com/nodeapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 39.45.62.105, server: movies-app.saedhamdan.com, request: "GET / HTTP/1.1", upstream: "http://unix:/home/admin/web/movies-app.saedhamdan.com/nodeapp/app.sock:/", host: "movies-app.saedhamdan.com"
2020/05/04 18:37:34 [crit] 5009#5009: *5 connect() to unix:/home/admin/web/movies-app.saedhamdan.com/nodeapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 39.45.62.105, server: movies-app.saedhamdan.com, request: "GET / HTTP/1.1", upstream: "http://unix:/home/admin/web/movies-app.saedhamdan.com/nodeapp/app.sock:/", host: "movies-app.saedhamdan.com"
2020/05/04 18:39:38 [crit] 5623#5623: *1 connect() to unix:/home/admin/web/movies-app.saedhamdan.com/nodeapp/app.sock failed (2: No such file or directory) while connecting to upstream, client: 39.45.62.105, server: movies-app.saedhamdan.com, request: "GET / HTTP/1.1", upstream: "http://unix:/home/admin/web/movies-app.saedhamdan.com/nodeapp/app.sock:/", host: "movies-app.saedhamdan.com"
 

My app.js code is following

         const http = require('http')

         const path = require('path')

         var rootPath = path.normalize(__dirname)

        #const port = rootPath + '/app.sock'

        const port = '/home/admin/web/novies-app.saedhamdan.com/nodeapp/app.sock'

        const requestHandler = (request, response) => {
          console.log(request.url)
          response.end('Hello Node.js Server!')
        }
        const server = http.createServer(requestHandler)

        server.listen(port, (err) => {
          if (err) {
            return console.log('something bad happened', err)
          }

          console.log(`server is listening on ${port}`)
        })

**Comment by logico-dev** [comment]
There is a typo I think. The name of the directory is movies-app.saedhamdan.com but you write it with a n (**n**ovies-app.saed...)

```
 const port = '/home/admin/web/novies-app.saedhamdan.com/nodeapp/app.sock'
```

**Comment by hassaan-dev** [comment]
Sorry for that typo. I changed the spell but issue is still.
I just notice that .sh file might not run. So I changed the permission of /usr/local/vesta/data/templates/web/nginx/NodeJS.sh

After changing permission and rebuilding web domain config, I found PM2 message on screen with error below.

>[PM2] Spawning PM2 daemon with pm2_home=/home/admin/.pm2
[PM2] PM2 Successfully daemonized
Use --update-env to update environment variables
[PM2][ERROR] Process or Namespace /home/admin/web/movies-app.saedhamdan.com/nodeapp/app not found
chmod: cannot access ‘/home/admin/web/movies-app.saedhamdan.com/nodeapp/app.sock’: No such file or directory

**Comment by hassaan-dev** [comment]
Any update on this? Actually, I am waiting for this @logico-dev

**Comment by logico-dev** [comment]
Please go to your nodeapp directory and post the output of

`pwd`

**Comment by hassaan-dev** [comment]
Output of `pwd`

> /home/admin/web/movies-app.saedhamdan.com/nodeapp

**Comment by hassaan-dev** [comment]
Any update?

**Comment by mylastore** [comment]
Question? what is "The app must listen on a UNIX socket" I am new to this concept what does this mean?

**Comment by logico-dev** [comment]
Hi, yes, here is all the info you need.
- The same question on [stackoverflow](https://stackoverflow.com/questions/7045614/can-node-js-listen-on-unix-socket)
 - Here is the [Node documentation ](https://nodejs.org/api/net.html#net_server_listen_path_backlog_callback)
- Unix sockets on [ExpressJS](https://expressjs.com/sk/api.html#app.listen_path_callback)
